name: Deploy DzArabic Extensions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Grant Gradle permissions
        run: chmod +x ./extensions/gradlew
      
      - name: Build Extensions
        working-directory: ./extensions
        run: ./gradlew build --refresh-dependencies
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: |
            extensions/build/libs/*.jar
            extensions/build/reports/tests/**/*