name: Deploy DzArabic Extensions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build Extensions
        working-directory: ./extensions
        run: |
          chmod +x gradlew
          ./gradlew clean build --refresh-dependencies --stacktrace
      
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: extensions/build/libs/*.jar